### ISSUE TITLE
[STS] Can the extension remove extraneous code?

### ISSUE THREAD

**Issue by dnknn** [pwhite2/simple-tab-sorter#10]
Hello:) Would you like to ask whether the extension collects user privacy or tracks user behavior?

Why do need `analytics` code ?

Don't want extraneous code to affect browser performance or collection behavior.

----
<img align=right width=50% src=https://user-images.githubusercontent.com/10995302/107740248-a0a0dd00-6d45-11eb-9951-74f6341e8274.png>

I am wandering to choose, here is a very simple extension, without any extraneous code.
- **Sort Tabs by URL**
https://chrome.google.com/webstore/detail/ahpnnhpfemfgifkjpfoalamhdchhppkm

**Comment by pwhite2** [comment]
Hi @dnknn.

The analytics code only tracks that the extension is loaded and that the sort button was clicked. I added it in the first release of the extension because I wanted to know whether the extension was being frequently used or whether people might be installing the extension, sorting once or twice, then forgetting it's there. It was important to me to have an idea of how the extension was being used to justify further development effort rather than investing it in my next project.

Since the number of users has consistently grown, I've decided to remove the analytics code in the next patch release v0.3.1, which I hope to submit to the Chrome Web Store sometime tomorrow. I'm releasing v0.3.1 because of the removal of The Great Suspender and the numerous resulting forks, but removing the analytics code is simple enough to add to the release.

I'll be honest, you're probably better off with the extension you mentioned if you're looking for the simplest thing that works and you only need to sort by URL with no exceptions - the STS codebase would be a heck of a lot simpler if that's all it did. However, that would seem to be an inadequate solution if you want something under somewhat active development, if you're using a fork of The Great Suspender, or you want more flexible sorting options like STS's "Sort By: Custom" settings...

**Comment by dnknn** [comment]
Understand, thank you very much for your detailed and enthusiastic reply, thanks again!

**Comment by dnknn** [comment]
@pwhite2  Your extension and his extension, the biggest difference is the hotkey 👇

`chrome://extensions/shortcuts#:~:text=Simple Tab Sorter`

- ## If you define `Alt+U` as a hotkey , 
　　⚔ 👍His expansion can be sorted immediately !
　　⚔ 👎Your extension can't do it! because popup is displayed

---

- ## So can you add a hotkey for one-key sorting ❓

**Comment by pwhite2** [comment]
@dnknn You're quite welcome. Please do me a favor and submit your shortcut request as a separate request so I don't forget it and can track it separately. I can't commit to when I'll have time to get started on v0.4.0, since I've had my hands full with work & family lately, but I'll look into this once I do.

**Comment by dnknn** [comment]
Sorry, I'm really sorry, I remembered it wrong, there is no problem, I take it back!

**Comment by pwhite2** [comment]
@dnknn No problem at all, thanks for the update!
