### ISSUE TITLE
[STS] Remove duplicate tabs while sorting

### ISSUE THREAD

**Issue by ahollmann** [pwhite2/simple-tab-sorter#16]
Removing duplicate tabs while sorting would be really useful for me.

Enabling this feature using a checkbox would be nice.

Thanks for your work. This extensions is great.

**Comment by pwhite2** [comment]
Thanks @ahollmann , I appreciate the feedback.

That's something I've considered but haven't gotten around to experimenting with since there are already some pretty good duplicate tab prevention/remover extensions available (I use Clutter Free) and I've been trying to focus my limited STS time on features that might provide unique value or fall squarely within the domain of "tab sorting".

If I were to take a stab at this, a couple things immediately come to mind...

1. STS was designed to operate only in the browser window that its icon is clicked on to trigger the sort action - it's not designed to be triggered whenever a new tab is opened and, if it were to remove duplicate tabs, it would only do so within the current window - it would allow tabs that are duplicated across separate windows, which is something that dedicated duplicate tab remover/prevention extensions appear to handle well.
2. When duplicates are found, which tab would you prefer to close - the most recently used or the one with the most history? I can see people having different preferences and, off the top of my head, I vaguely recall that the chrome API doesn't track the "last opened/viewed" date/time, so STS would have to do that, which would increase in a larger memory footprint, which may or may not be acceptable depending on how many tabs you keep open...

With all of the above in mind, is having this capability in STS still desirable to you?

Thanks,
Peter

**Comment by pwhite2** [comment]
@ahollmann - Hi Andreas, sorry it took so long, but I implemented your request in [Super Tab Sorter](https://github.com/pwhite2/super-tab-sorter) and just published it on the Chrome Web Store.

The new extension isn't appearing in the web store search yet, but [this](https://chromewebstore.google.com/detail/super-tab-sorter/jjhppbooocacaccnhjninhmigbfmpnkh) is its direct link.
